### ISSUE TITLE
How to make 2d picture of face with extracted textures?

### ISSUE THREAD

**Issue by Maelstrom2014** [YangXingchao/makeup-extract#2]
How to make 2d picture (like input image) of face with extracted textures?
Do this code exist? Thanx!

**Comment by YangXingchao** [comment]
sorry for the late reply! 
we uploaded step_5 for rendering a 3D face using these textures.

**Comment by yeyu-cpu** [comment]
how to turn a 3D face into a final result image(with background)? Thankyou!

**Comment by YangXingchao** [comment]
We made modifications to the related face segment script in libs. Please check the corresponding code for step_0 and step_5.
