### ISSUE TITLE
Error in stage 1

### ISSUE THREAD

**Issue by YoucanBaby** [YangXingchao/makeup-extract#6]
Dear author,

When I run `python step_1_coarse_reconstruction.py`, I get the error as follows:

```
creating the FLAME Decoder
[F glutil.cpp:332] eglGetDisplay() failed
Aborted (core dumped)
```

May I ask how to solve this problem?

Best regards.

**Comment by YoucanBaby** [comment]
Change [this line](https://github.com/YangXingchao/makeup-extract/blob/3a2feb3f32aed6482f3f80772a53ac7109c02b5f/step_1_coarse_reconstruction.py#L56) to `glctx = dr.RasterizeCudaContext()` to solve this problem.

**Comment by mercurystraw** [comment]
That works🫡! I had been debugging this issue for quite a while, and finally fixed it by following your solution. 

Really appreciate your help and the time you took to share it.

BTW, I made changes in stage 1, stage 3, and stage 5. Then it runs properly.
